dbt_db:
  outputs:
    dev:
      catalog: mycatalog
      host: adb-4135443550113658.18.azuredatabricks.net
      http_path: /sql/1.0/warehouses/27b89470a07f84ae
      schema: dev
      threads: 1
      token: ${{ secrets.DATABRICKS_TOKEN }}
      type: databricks
    
    prod:
      catalog: mycatalog
      host: adb-4135443550113658.18.azuredatabricks.net
      http_path: /sql/1.0/warehouses/27b89470a07f84ae
      schema: prod
      threads: 1
      token: ${{ secrets.DATABRICKS_TOKEN }}
      type: databricks
  target: dev