name: Deploy simple_project to DEV

concurrency: 1

on:
  workflow_dispatch:

  push:
    branches:
      - dev
env:
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN}}

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip
      - run: pip install wheel
      - run: pip3 install wheel
      - run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest
      
      - uses: databricks/setup-cli@main

      # Deploy the bundle
      - run: databricks bundle deploy --var="DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN}}"
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev
